# Generated by Django 3.0.2 on 2020-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram Password'),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Instagram username'),
        ),
    ]
